name: (Dev) Build and deploy on Itch.io 

on:
  workflow_dispatch:

jobs:
  buildForSomePlatforms:
    name: Build for ${{ matrix.targetPlatform }} with itchio channel ${{ matrix.itch_channel }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - targetPlatform: StandaloneWindows64   # Build a Windows 64-bit standal
            itch_channel: windows
          - targetPlatform: StandaloneLinux64 # Build a Windows 64-bit standal
            itch_channel: linux
          - targetPlatform: StandaloneOSX # Build a macOS standalone (Intel 64-bit).
            itch_channel: mac
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: game-ci/unity-builder@v2
        id: BuildStep
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          buildName: ${{ secrets.UNITY_PROJECT_NAME}}
          targetPlatform: ${{ matrix.targetPlatform }}
          versioning: Semantic
      #- uses: actions/upload-artifact@v2
       # with:
        #  name: Build
         # path: build
      - name: Rename game folder
        run: |
          mv build/${{ matrix.targetPlatform }} build/RombTaider
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.SOLAR_BUTLER_CREDENTIALS }}
          CHANNEL: dev-${{ matrix.itch_channel }}
          ITCH_GAME: ${{ secrets.ITCH_GAME }}
          ITCH_USER: ${{ secrets.ITCH_USER }}
          PACKAGE: build
          VERSION: ${{ steps.BuildStep.outputs.buildVersion }}
      - run: echo ${{ steps.BuildStep.outputs.buildVersion }}
      - uses: papeloto/action-zip@v1
        env:
          zipName: ${{ secrets.UNITY_PROJECT_NAME }}-${{ matrix.itch_channel }}-${{ steps.BuildStep.outputs.buildVersion }}.zip
        with:
          files: build
          dest: ${{ env.zipName }}
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_TSM }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Build of ${{ secrets.UNITY_PROJECT_NAME }} for ${{ matrix.itch_channel }} completed
          document: ${{ env.zipName }}
          
  sendTagAnnotations:
    name: Send tag annotations if tag exists
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: ericcornelissen/git-tag-annotation-action@v1
        id: tag_data
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_TSM }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Important changes:\n${{ steps.tag_data.outputs.git-tag-annotation }}
