name: tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          mkdir renamed
          mkdir build
          mkdir build/Standalone
          cd -r build/Standalone renamed
          cd renamed
          ls
          echo *********
          cd ..
          mv renamed/Standalone renamed/RombTaider
          cd renamed
          ls
          
          
        
