name: tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_TSM }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: Test\ntest
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_TSM }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%s" }}
          
          
        
