name: tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: output
        id: versioning
        run: |
          echo "::set-output name=version::1.2.3" 
      - name: Tag
        run: |
          version=${{ steps.versioning.outputs.version }}-pre
          git tag v$version
          git push origin v$version
    env:
      version: ${{ steps.versioning.outputs.version }}
      
  out:
    runs-on: ubuntu-latest
    name: output variable
    steps:
      - name: asd
        run: |
          echo ${{ jobs.test.env.version }}
          
        
