name: tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
#       matrix:
#         cond: [asd, qwe]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: version
        run: |
          strindex() {
            x="${1%%$2*}"
            [[ "$x" = "$1" ]] && echo -1 || echo "${#x}"
          }
          describe=$(git describe --tags --long --match v[0-9]*)
          echo $describe
          majorindex=$(strindex $describe ".")
          major=${describe:0:majorindex+1}
          minorsub=${describe:majorindex+1}
          minorsub=$(echo "$minorsub") | tr - .)
          minorindex=$(strindex $minorsub ".")
          minor=${minorsub:0:minorindex+1}
          patchindex=$(strindex $describe "-")
          patch=${describe:patchindex+1:-9}
          version=$major$minor$patch
          echo $version
          
