name: tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cond: [asd, qwe]
    steps:
#       - uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
      - name: output
        if: matrix.cond == asd
        run: echo nice

          
        
