name: tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set changes variable
        id: changes
        run: |
          changes=$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%s"
          echo "::set-output name=changes::changes)"
          echo "::set-output name=lasttag::$(git describe --tags --abbrev=0)"
      - run: |
          echo ${{ steps.changes.outputs.changes }}
#       - uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.TELEGRAM_TO_TSM }}
#           token: ${{ secrets.TELEGRAM_TOKEN }}
#           message: Changes since version ${{ steps.changes.outputs.lasttag }}":"
#       - uses: appleboy/telegram-action@master
#         with:
#           to: ${{ secrets.TELEGRAM_TO_TSM }}
#           token: ${{ secrets.TELEGRAM_TOKEN }}
#           message: ${{ steps.changes.outputs.changes }}
          
          
        
