name: tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Echo refs
        run:  |
          echo 'asd -> ${GITHUB_REF#refs/*/}'
