name: tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        val: [asd, qwe]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: output
        if: matrix.val == asd
        run: echo nice

          
        
