name: tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          mkdir renamed
          cp -r Assets/Sprites renamed
          mv renamed/Sprites renamed/Qwes
          ls
          echo ***
          cd Assets/Sprites
          ls
          echo ***
          cd ..
          cd renamed
          ls
          echo***
          cd Qwes
          ls
          
        
