name: tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --tags --force
      - uses: ericcornelissen/git-tag-annotation-action@v1
        id: tag_data
      - run: echo ${{ github.ref }}
      - name: Echo tag if tag exists
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo ${{ steps.tag_data.outputs.git-tag-annotation }}
      - name: Echo asd if is main branch
        if: startsWith(github.ref, 'refs/branch/main')
        run: echo ${{ steps.tag_data.outputs.git-tag-annotation }}
        
