name: tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: env set
        env:
          val: 42
        run: echo ${{ env.val }}
      - run: echo ${{ env.val }} again
          
          
        
