name: tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: output
        id: versioning
        run: |
          echo "::set-output name=version::1.2.3" 
      - name: Tag
        run: |
          version=${{ steps.versioning.outputs.version }}
          git tag v$version
          git push origin v$version
          
          
        
