name: tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        asd: [qwe, asd]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: echo $(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:"%s")
          
          
        
