name: tests

on:
  workflow_dispatch:

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: ericcornelissen/git-tag-annotation-action@v1
        id: tag_data
      - name: Echo tag annotation
        run: echo ${{ steps.tag_data.outputs.git-tag-annotation }}
